### ISSUE TITLE
Go over SoS feedback on Dragoon and add appropriate task cards

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/LaitsV3#34]
Ignacio writes: 

As part of the class activities I asked the students to briefly comment on their experience with Dragoon and to suggest some ideas for improvement. In general I have to say that students are very happy with the software, and most of the have had little problems in using it.

Attachment:  [Dragoon Improvement Suggestions from Students.docx](https://github.com/Dragoon-Lab/LaitsV3/files/822631/Dragoon.Improvement.Suggestions.from.Students.docx)

**Comment by vanlehn** [comment]
[Dragoon.Improvement.Suggestions.from.Students.docx](https://github.com/Dragoon-Lab/LaitsV3/files/901004/Dragoon.Improvement.Suggestions.from.Students.docx)

**Comment by vanlehn** [comment]
see comments
