### ISSUE TITLE
Leaderboard does not highlight the current student

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/LaitsV3#45]
There might be work to do on the LMS side too.  Let me know if that's the case.

**Comment by sachingrover211** [comment]
I just tested this on the copy of the code for topomath. The only case is username is not being sent from LMS. Please check that or let me know I will do it. This is a very small change. I mean an extra small change.

**Comment by jonwetzel** [comment]
@sachingrover211 That's been assigned to @riteshsamala in https://github.com/Dragoon-Lab/LMS/issues/95 Thanks!
