### ISSUE TITLE
Fix compile warnings in Dragoon

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/LaitsV3#53]
To see the list of warnings, run the build (go to <laits repo path>/www and run "gulp build"), then open the report (found in <laits repo path>/release/www/build-report.txt) and search for ": WARNING" to find them easily.

**Comment by dharanisakary** [comment]
Here is the standard response from dojo regarding warnings - https://bugs.dojotoolkit.org/ticket/15903

**Comment by jonwetzel** [comment]
@dharanisakary ok, we can ignore the warnings in dojo and any libraries we're importing.  Please fix any warnings specific to our code.
