### ISSUE TITLE
Change LRS support for Electronix Tutor

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/LaitsV3#72]
Use branch ET-xapi

- [ ] Disable the code for ETConnector.js.  We'll delete it in a future task.
- [ ] Add the two .js files https://github.com/andrewtackett/ET_Recommender/tree/master/hostedResources/lib to our code base.  These are the libraries we need to communicate with the LRS.
- [ ] Create a config file to somehow pass in the authentication information.  List it on .gitignore and never upload it to github.
- [ ] Write a function that takes in the problem name and gives back the Learning_Resource_Name from the big spreadsheet.
- [ ] Add code to call sendKCScore when the user clicks "done".  Do this ONLY if the server path equals "ET".  (See the pal3 code which uses tincan.js for example of how to do this.)
   - First argument should be "DRAGOON", 
   - The second should be the LearningResourceName from the spreadsheet (need new code to generate this string)
  - The third will be the dictionary we used to send in tincan.js or ETConnector--communicate with Andrew to finalize this.
  - More details on these arguments can be found in the email thread.

**Comment by jonwetzel** [comment]
@dharanisakary Deadline for this task is Friday.  Testing will be required, so aim to have the code done midweek to get info on how to test it with Andrew Tackett.  (He should be able to give us a login on their moodle to test with.)

Prioritize getting the connection working first (everything but the 3rd argument) since in the worst case we can just send what we were sending before.

**Comment by dharanisakary** [comment]
I found that there were few problems for which we do not pass expected KC's to Electronix Tutor.

positive-biased-parallel-positive-limiter - We dont pass KC resistor_behavior [Expected - ["kirchhoffs_voltage_law", "ohms_law_voltage", "resistor_behavior", "parallel_positive_limiter_with_positive_bias_behavior", "diode_behavior_reverse", "diode_behavior_forward"]]
positive-biased-series-positive-limiter - We dont pass KC resistor_behavior [Expected -["series_positive_limiter_with_positive_bias_behavior", "kirchhoffs_voltage_law", "ohms_law_voltage", "resistor_behavior", "diode_behavior_reverse", "diode_behavior_forward"] ]
diode-resistor - We dont pass KCs resistor_behavior, zener_diode_behavior_reverse [Expected - ["kirchhoffs_voltage_law", "ohms_law_voltage", "resistor_behavior", "zener_diode_behavior_reverse", "diode_behavior_reverse", "diode_behavior_forward"]]

**Comment by jonwetzel** [comment]
@dharanisakary After looking at the list, I think we can try to add those missing KCs (schemas) to the models.  We'll open them in author mode, add the missing schemas based on other problems which use have those schemas, and then use the export problem feature (in the settings and times menu) to dump them to json files, which we'll commit to git over the old versions.  This process can be done on a local system and then pushed.

One thing we need to know is the deadline.  Can you ask Andrew how soon they are needed?  I don't think it will take long to do, but I want to prioritize it correctly.  Thanks!

**Comment by jonwetzel** [comment]
@vanlehn I've added the missing schema to the two limiter problems.  For the third and final problem they reported that "diode-resistor" is missing zener_diode_behavior_reverse --but this problem doesn't appear to involve a zener diode!  (It's not mentioned in the text anywhere.)  Can I tell them that's a bug in their KC list?

**Comment by jonwetzel** [comment]
@dharanisakary I've added the missing resistor schemas and pushed the new jsons files to the repot.  They're already on the server, so you won't need to pull.  Please test them and see if the errors stop (aside from the zener_diode_behavior_reverse one, which I think is a bug on Andrew's side--pending confirmation from Kurt above).

Also, please add ET-config.json to .gitignore  Thanks!

**Comment by vanlehn** [comment]
yes

**Comment by jonwetzel** [comment]
Thanks @vanlehn, I'll let them know.
